version: '3.7'
services:
  app:
    build: .
    container_name: elasticvue
    environment:
        - ELASTICSEARCH_HOST=http://elasticsearch
        - ELASTICSEARCH_PORT=9200
        - ELASTIC_CLIENT_TYPE=docker
    restart: unless-stopped
    ports:
      - 8080:8080
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=/.*/
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300

