FROM node:22.5.1-bookworm
ARG USERID=1000

RUN apt-get update -qq \
        && apt-get upgrade -y \
        && apt-get install -y \
            zip \
        && apt-get clean \
        && apt-get autoclean \
        && apt-get autoremove -y \
        && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

RUN npm install --global web-ext

COPY package.json .
COPY yarn.lock .

RUN yarn install
COPY . .

RUN chown -R $USERID:$USERID /app
USER $USERID

ENTRYPOINT ["/bin/bash"]