FROM node:22.20.0-bookworm
ARG USERID=1000
ENV APP_HOME=/app

RUN if ! id -u $USERID > /dev/null 2>&1; then useradd --uid $USERID -m dev; fi

RUN mkdir -p $APP_HOME

RUN apt-get update -qq \
        && apt-get install -y zip \
        && apt-get clean \
        && apt-get autoclean \
        && apt-get autoremove -y \
        && rm -rf /var/lib/apt/lists/*

WORKDIR $APP_HOME

RUN npm install --global web-ext

COPY . .

RUN npm install

RUN chown -R $USERID:$USERID $APP_HOME

USER $USERID

ENTRYPOINT ["/bin/bash"]
