FROM ubuntu:jammy
ARG USERID=1000

ENV NODE_VERSION=22
ENV APP_HOME=/app

RUN useradd --uid $USERID -m dev
RUN mkdir -p $APP_HOME
RUN chown -R $USERID:$USERID $APP_HOME

WORKDIR $APP_HOME

RUN apt-get update && \
    apt-get install -y wget curl vim gpg \
    && apt-get clean \
    && apt-get autoclean \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

USER $USERID

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y

USER root

RUN mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_VERSION.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y nodejs yarn \
	&& apt-get clean \
	&& apt-get autoclean \
	&& apt-get autoremove -y \
	&& rm -rf /var/lib/apt/lists/*

# download old versions because of EGL issues, see https://github.com/h3poteto/fedistar/issues/1717
RUN mkdir -p /tmp/ubuntu-packages \
    && cd /tmp/ubuntu-packages \
    && wget https://launchpadlibrarian.net/723972773/libwebkit2gtk-4.1-0_2.44.0-0ubuntu0.22.04.1_amd64.deb \
    && wget https://launchpadlibrarian.net/723972761/libwebkit2gtk-4.1-dev_2.44.0-0ubuntu0.22.04.1_amd64.deb \
    && wget https://launchpadlibrarian.net/723972770/libjavascriptcoregtk-4.1-0_2.44.0-0ubuntu0.22.04.1_amd64.deb \
    && wget https://launchpadlibrarian.net/723972746/libjavascriptcoregtk-4.1-dev_2.44.0-0ubuntu0.22.04.1_amd64.deb \
    && wget https://launchpadlibrarian.net/723972735/gir1.2-javascriptcoregtk-4.1_2.44.0-0ubuntu0.22.04.1_amd64.deb \
    && wget https://launchpadlibrarian.net/723972739/gir1.2-webkit2-4.1_2.44.0-0ubuntu0.22.04.1_amd64.deb \
    && wget https://launchpadlibrarian.net/606433947/libicu70_70.1-2ubuntu1_amd64.deb \
    && wget https://launchpadlibrarian.net/606433941/libicu-dev_70.1-2ubuntu1_amd64.deb \
    && wget https://launchpadlibrarian.net/606433945/icu-devtools_70.1-2ubuntu1_amd64.deb \
    && wget https://launchpadlibrarian.net/595623693/libjpeg8_8c-2ubuntu10_amd64.deb \
    && wget https://launchpadlibrarian.net/587202140/libjpeg-turbo8_2.1.2-0ubuntu1_amd64.deb \
    && wget https://launchpadlibrarian.net/592959859/xdg-desktop-portal-gtk_1.14.0-1build1_amd64.deb

RUN apt-get update \
    && apt-get install -y build-essential \
                          file \
                          libssl-dev \
                          libgtk-3-dev \
                          libxdo-dev \
                          libayatana-appindicator3-dev \
                          librsvg2-dev \
    && apt-get install -y /tmp/ubuntu-packages/*.deb \
    && rm -rf /tmp/ubuntu-packages \
    && apt-get clean \
    && apt-get autoclean \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

USER $USERID
