
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"             # LocalStack edge
      - "4510-4559:4510-4559"   # external-service port range
    environment:
      - SERVICES=iam,sts,es
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/var/lib/localstack
      - ES_ENDPOINT_STRATEGY=path
      - OPENSEARCH_ENDPOINT_STRATEGY=path
      - DEBUG=1
      - EXTERNAL_SERVICE_PORTS_START=4510         # inclusive
      - EXTERNAL_SERVICE_PORTS_END=4559           # exclusive
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:5174,http://localhost:9200
      - EXTRA_CORS_ALLOWED_HEADERS=x-api-key
    volumes:
      - localstack_data:/var/lib/localstack
      - ./init-iam-es.sh:/etc/localstack/init/ready.d/init-iam-es.sh
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack_data: